#!/bin/sh
#

# run Black and flake8 on all .py files in the repo
black .
flake8 .
yamllint .

# git-crypt check for unencrypted file warnings adapted from https://www.gitmemory.com/issue/AGWA/git-crypt/45/614607121
if [ -d ".git-crypt" ]; then
    git-crypt status | grep "\*\*\* WARNING"; test $? -eq 1
fi
